services:
  - type: web
    name: pyquotex-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn live_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYQUOTEX_EMAIL
        sync: false
      - key: PYQUOTEX_PASSWORD
        sync: false